name: hexa-policy-opa

services:
  bundle-server:
    image: hexaopa
    container_name: hexa-bundle-server
    ports:
      - "8889:8889"
    command: /app/hexaBundleServer
    environment:
      PORT: 8889
      HEXA_CERT_DIRECTORY: "/home/certs"
      SERVER_CERT: "/home/certs/server-cert.pem"
      SERVER_KEY: "/home/certs/server-key.pem"
      BUNDLE_DIR: "/home/resources/bundles"
    volumes:
      - "./deployments/hexaBundleServer/resources:/home/resources"
      - "./.certs:/home/certs:ro"

  hexa-opa-sidecar:
    image: hexaopa
    container_name: hexa-opa-server
    ports:
      - "8887:8887"
    depends_on:
      - bundle-server
    command: /app/hexaOpa run --server --addr :8887 --log-level debug -c /home/config/config.yaml
    environment:
      # These environment values are referenced in ./deployments/hexaOpaServer/config/config.yaml
      HEXA_CERT_DIRECTORY: "/home/certs"
      HEXA_CONFIG_URL: "https://hexa-bundle-server:8889"
      HEXA_CA_CERT: "/home/certs/ca-cert.pem"
    volumes:
      - "./deployments/hexaOpaServer/config:/home/config:ro"
      - "./deployments/hexaOpaServer/.opa:/app/.opa"
      - "./.certs:/home/certs:ro"

  hexa-authzen:
    container_name: hexa-authzen
    image: hexaopa
    ports:
      - "8888:8888"
    command: /app/hexaAuthZen
    environment:
      PORT: 8888
      AUTHZEN_BUNDLE_DIR: "/home/authZen/bundles"
      AUTHZEN_USERPIP_FILE: "/home/authZen/users.json"
      AUTHZEN_TOKEN_DIRECTORY: "/home/certs"
      AUTHZEN_TKN_MODE: "BUNDLE"
    volumes:
      - "./deployments/authZen:/home/authZen"
      - "./.certs:/home/certs:ro"

  demo-app:
    image: hexaopa
    container_name: hexa-demo
    ports:
      - "8886:8886"
    command: /app/hexaIndustriesDemo
    depends_on:
      - hexa-opa-sidecar
    environment:
      PORT: 8886
      OPA_SERVER_URL: http://opa-agent:8887/v1/data/hexaPolicy
