export PORT=8080
export AUTHZEN_BUNDLE_DIR=deployments/authZen/bundles
export AUTHZEN_USERPIP_FILE=deployments/authZen/users.json
export AUTHZEN_TKN_DIRECTORY=
export AUTHZEN_TKN_PRIVKEYFILE=
export AUTHZEN_TKN_DISABLE=false