PORT=8080
AUTHZEN_BUNDLE_DIR=deployments/authZen/bundles
AUTHZEN_USERPIP_FILE=deployments/authZen/users.json
HEXA_TKN_DIRECTORY=./.certs
HEXA_TKN_PRIVKEYFILE=
HEXA_TKN_MODE=ANON
HEXA_TKN_ISSUER=authZen